## 1. 수박수박수박수박?

In [1]:
n = 1

In [25]:
if n % 2 == 0:
    print("수박" * (n//2))
else:
    print("수박" * (n//2) + '수')

수


In [26]:
def solution(n):
    if n % 2 == 0:
        return "수박" * (n//2)
    else:
        return "수박" * (n//2) + '수'

In [28]:
solution(2)

'수박'

## 

## 2. 큰 수 만들기

In [2]:
import numpy as np

In [3]:
n = "4177252841"

In [281]:
n[0:2]

'41'

In [300]:
l = len(n)

In [301]:
l

10

In [4]:
num = np.array([int(n[x]) for x in range(len(n))])

In [5]:
num

array([4, 1, 7, 7, 2, 5, 2, 8, 4, 1])

In [10]:
num[1:3]

array([1, 7])

In [302]:
k=4
container = np.zeros(l-k)
container

array([0., 0., 0., 0., 0., 0.])

In [303]:
for i in range(l-len(container)+1):
    num1 = n[i:i+len(container)]
    for j in range(len(container)):
        if int(container[j]) < int(num1[j]):
            container[j] = num1[j]
            try:
                if int(container[j]) == int(container[j+1]):
                    container[j+1] = 0
            except:
                pass
            
''.join([str(int(x)) for x in container])

'775841'

In [296]:
container

array([7., 7., 5., 8., 4., 1.])

In [297]:
''.join([str(int(x)) for x in container])

'775841'

In [230]:
num[0:2]

[1, 9]

In [17]:
import numpy as np

def solution(number, k):
    l = len(number)
    num = [int(number[x]) for x in range(len(number))]
    container = num[:l-k]
    
    for i in range(1, l - len(container) + 1):
        num1 = num[i:i+len(container)]
        
        for j in range(len(container)):
            if container[j] < num1[j]:
                container[j] = num1[j]
                
                try:
                    if container[j] == container[j+1]:
                        container[j+1] = 0
                except:
                    pass
    
    return ''.join([str(int(x)) for x in container])

In [18]:
solution("4177252841", 4)

[4 1 7 7 2 5]
[1 7 7 2 5 2]
[7 7 2 5 2 8]
[7 2 5 2 8 4]
[2 5 2 8 4 1]


'775841'

In [308]:
for i in range(4):
    print(i)

0
1
2
3


In [194]:
k = 5
num = np.array([1,2,3,1,2,3,4])
l = len(num)
containers = num[:l-k]
containers

array([1, 2])

In [195]:
for i in range(1, l-len(containers)+1):
    num1 = num[i:i+len(containers)]
    if i == (len(num)-len(containers)):
        if (containers < num1).sum() != 0:
            idx = np.where(containers < num1)[0]
            containers[idx] = num1[idx]
            
    else:
        if (containers < num1).sum() != 0:
            idx = np.where(containers < num1)[0][0]
            containers[idx] = num1[idx]

[2 3]
1
1
[2 2]
[3 1]
2
2
[3 2]
[1 2]
3
3
[3 2]
[2 3]
4
4
[3 3]
[3 4]
5
5
[3 4]


In [196]:
containers

array([3, 4])

In [197]:
num1 = num[1:3]
num1

array([4, 3])

In [200]:
sum(containers < num1)

1

In [178]:
idx.sum()

2

In [142]:
idx = np.where(containers < num1)[0]

In [141]:
idx

1

In [112]:
containers[idx] = num1[idx]

In [113]:
containers

array([3, 3, 4])

In [35]:
if containers.sum() == containers[0] * 2:
    containers[1] = 0

In [36]:
containers

array([9, 4])

In [287]:
import numpy as np

def solution(number, k):
    l = len(number)
    num = [int(number[x]) for x in range(len(number))]
    containers = np.array(num[:l-k])

    for i in range(1, l-len(containers)+1):
        num1 = num[i:i+len(containers)]

        if i == (len(num)-len(containers)):
            
            containers[-(k-1):] = num1[-(k-1):]

        else:
            if True in (containers < num1):
                idx = np.where(containers < num1)[0][0]
                containers[idx:] = num1[idx:]
        
        
        
    return ''.join([str(int(x)) for x in containers])

In [297]:
solution('1231234', 3)

containers: [1 2 3 1]
num1 [2, 3, 1, 2]
containers [2 3 1 2]
num1 [3, 1, 2, 3]
containers [3 1 2 3]
num1 [1, 2, 3, 4]
containers [3 1 2 3]
num1 [1, 2, 3, 4]
containers [3 1 3 4]


'3134'

In [209]:
if sum(list(containers < num1)) != 0:
    print(12)

12


In [210]:
True in [True, False]

True

In [408]:
np.where(np.array([3,1,2,3]) < np.array([1,2,3,4]))

(array([1, 2, 3], dtype=int64),)

In [290]:
containers = np.array([3,1,2,3])
num1 = [1,2,3,4]

In [293]:
containers[1:] = num1[1:]

In [294]:
containers

array([3, 2, 3, 4])

In [335]:
import numpy as np

def solution(number, k):
    l = len(number)
    num = [int(number[x]) for x in range(len(number))]
    containers = np.array(num[:l-k])

    for i in range(1, l-len(containers)+1):
        num1 = num[i:i+len(containers)]

        if i == (len(num)-len(containers)):
            
            containers[-(k-1):] = num1[-(k-1):]

        else:
            if True in (containers < num1):
                idx = np.where(containers < num1)[0][0]
                containers[idx:] = num1[idx:]
        
        
        
    return ''.join([str(int(x)) for x in containers])

In [337]:
solution('4177252841', 2)

'47725281'

In [313]:
k=4
num = '3177252841'
num[-(k-1):]

'841'

In [401]:
number = "4177252841"
num = [int(number[x]) for x in range(len(number))]
num

[4, 1, 7, 7, 2, 5, 2, 8, 4, 1]

In [402]:
k = 4

In [403]:
# container 는 6칸
l = len(num) - k
start = np.argmax(num[:k+1])
start

2

In [404]:
containers = np.array(num[start:start+l])
containers

array([7, 7, 2, 5, 2, 8])

In [365]:
num = num[start:]
num

[7, 7, 2, 5, 2, 8, 4, 1]

In [426]:
import numpy as np

def solution(number, k):
    num = np.array([int(number[x]) for x in range(len(number))])
    l = len(num) - k
    start = np.argmax(num[:k+1])

    containers = np.array(num[start:start+l])

    num = np.array(num[start:])

    for i in range(1,len(num)-l+1):
        if True in (containers < num[i: i+l]):
            idx = np.where(containers < num[i: i+l])[0][0]
            containers[idx:] = num[i: i+l][idx:]
            
    result = ''.join([str(x) for x in containers])
    return result

In [427]:
solution('1924', 2)

'94'

In [400]:
containers < num1

array([False, False, False, False, False, False])

In [397]:
import numpy as np

def solution(number, k):
    num = [int(number[x]) for x in range(len(number))]
    l = len(num) - k
    start = np.argmax(num[:k+1])

    containers = np.array(num[start:start+l])

    num = num[start:]

    for i in range(1,len(num)-l+1):
        num1 = num[i: i+l]
        if True in (containers < num1):
            idx = np.where(containers < num1)[0][0]
            containers[idx:] = num1[idx:]
    
    return ''.join([str(x) for x in containers])

In [390]:
number = '4177252841'
num = np.array([int(number[x]) for x in range(len(number))])
num[4:12]

array([2, 5, 2, 8, 4, 1])

In [395]:
np.where(containers < num1)

(array([], dtype=int64),)

In [396]:
[False,True,True]

[False, True, True]

In [431]:
np.where(np.array([3,1,2,3]) < np.array([1,2,1,4]),  np.array([1,2,3,4]), np.array([3,1,2,3]))

array([3, 2, 2, 4])

In [1]:
import numpy as np

def solution(number, k):
    num = np.array([int(number[x]) for x in range(len(number))])
    l = len(num) - k
    start = np.argmax(num[:k+1])
    
    num = np.array(num[start:])
    
    containers = np.array(num[:l])

    for i in range(1,len(num)-l+1):
        num1 = num[i:i+l]
        if True in (containers < num1):
            idx = np.where(containers < num1)[0][0]
            containers[idx:] = num1[idx:]
            
    result = ''.join([str(x) for x in containers])
    return result

In [75]:
import numpy as np

def solution(number, k):
    num = np.array([int(number[x]) for x in range(len(number))])
    l = len(num) - k
    start = np.argmax(num[:k+1])
    
    num = np.array(num[start:])
    
    containers = np.array(num[:l])
                         
    for i in range(1,len(num)-l+1):
        num1 = num[i:i+l]
        try:
            idx, = np.where(containers < num1)
            containers[idx[0]:] = num1[idx[0]:]
        except:
            pass
    
    return ''.join([str(x) for x in containers])

In [90]:
solution('4177252841', 9)

'8'

In [71]:
a, = np.where(np.array([3,1,2,3]) < np.array([1,2,1,4]))

In [72]:
a

array([1, 3], dtype=int64)