In [ ]:
# 알고리즘 1:   
# starting point 설정
# starting point에서 가장 cost가 낮은 쪽으로 다리 건설
# 모든 노드를 지나칠 수 있는지 체크
## 가능?? 그럼 해당 cost 저장
## 불가능?? 그럼 pass
# 저장된 cost의 최솟값으로 리턴

In [1]:
import numpy as np

In [2]:
n = 4
costs = [[0,1,1],[0,2,2],[1,2,5],[1,3,1],[2,3,8]]

In [3]:
starting_points = list(np.unique([(x[0], x[1]) for x in costs]))

In [4]:
start = starting_points[0]
start

0

In [30]:
route = np.array(costs)
route

array([[0, 1, 1],
       [0, 2, 2],
       [1, 2, 5],
       [1, 3, 1],
       [2, 3, 8]])

In [38]:
route[:,2]

array([1, 2, 5, 1, 8])

In [42]:
np.where(start

True

In [60]:
start = 1
idx, = np.where((route[:,0] == start) | (route[:,1] == start))

In [69]:
low = np.argmin(route[idx][:,2])
route[low]

array([0, 1, 1])

In [70]:
# 알고리즘 2:   
# greedy 하게~
# cost가 가장 적게 드는 놈부터 골라서 건설 해부러~
# 이때, 연결되는 섬 카운트하고 비용은 게속 쌓아가
# stopping criterion: 섬 개수 만족 + 연결된 선이 (섬 개수 - 1) 일때

In [26]:
import numpy as np

In [33]:
n = 4
costs = [[0,1,1], [0,2,2],[1,2,5],[1,3,1],[2,3,8]]

In [34]:
costs_p = np.array(costs)

In [29]:
# 건설비용이 제일 작은 넘 추출
## iter = 1
low_idx = np.argmin(costs_p[:,2])
low_idx

0

In [ ]:
np.where((costs_p[:,2] == np.min(costs_p[:,2])) &  ,,)

In [36]:
costs_p[:,2] == np.min(costs_p[:,2])

array([ True, False, False,  True, False])

In [30]:
# 다리 건설 및 연결된 섬 저장
island = costs_p[low_idx][:2]
island

array([0, 1])

In [6]:
# 건설 비용 저장
total_c = costs_p[low_idx][-1]
total_c

1

In [7]:
# 건설했으니, costs에서 삭제 해야지~~~
costs_p = np.delete(costs_p, low_idx, axis=0)

In [8]:
## iter = 2
low_idx = np.argmin(costs_p[:,2])
low_idx

2

In [18]:
costs_p[low_idx][:2]

array([0, 2])

In [10]:
island = np.unique(np.append(island, costs_p[low_idx][:2]))
island

array([0, 1, 3])

In [11]:
total_c += costs_p[low_idx][-1]
total_c

2

In [12]:
costs_p = np.delete(costs_p, low_idx, axis=0)
costs_p

array([[0, 2, 2],
       [1, 2, 5],
       [2, 3, 8]])

In [14]:
## iter = 3
low_idx = np.argmin(costs_p[:,2])
low_idx

0

In [15]:
costs_p[low_idx][:2]

array([0, 2])

In [16]:
island = np.unique(np.append(island, costs_p[low_idx][:2]))
island

array([0, 1, 2, 3])

In [17]:
total_c += costs_p[low_idx][-1]
total_c

4

In [ ]:
import numpy as np

def solution(n, costs):
    
    costs_p = np.array(costs)
    island = np.array([])
    total_c = 0
    cnt = 0
    
    while True:
        low_idx = np.argmin(costs_p[:,2])

        island = np.unique(np.append(island, costs_p[low_idx][:2]))

        total_c += costs_p[low_idx][-1]

        costs_p = np.delete(costs_p, low_idx, axis=0)

        cnt += 1.

        if (len(island) == 4) & (cnt >= n-1):
            break
    
    return total_c