In [9]:
import numpy as np

In [10]:
def solution(key, lock):
    answer = True
    return answer

In [78]:
# 열쇠 90도 회전 함수
def rotate(m):
    N = len(m)
    ret = [[0] * N for _ in range(N)]
    for r in range(N):
        for c in range(N):
            ret[c][N-1-r] = m[r][c] 
    return np.array(ret)

In [39]:
# 열쇠 이동 함수
## key에서 1의 위치, lock에서 0의 위치를 비교하여 맞으면 True
def check(key, lock):
    for i in range(3):
        key = rotate(key)
        

ValueError: operands could not be broadcast together with shapes (3,2) (3,3) 

In [124]:
key = np.array([[1,0,0], [0,1,0], [0,0,0]])
lock = np.array([[0,0,0], [0,0,1], [0,1,0]])

In [63]:
# key의 1위치 저장
x,y = np.where(key == 1,)
key_idx = [(x[i]+1,y[i]+1) for i in range(len(x))]

In [64]:
# lock의 0위치 저장
x,y = np.where(lock == 0,)
lock_idx = [(x[i]+1,y[i]+1) for i in range(len(x))]

In [93]:
key_idx

[(1, 2), (2, 1), (3, 1)]

In [68]:
lock_idx

[(2, 3), (3, 2)]

In [79]:
key_90 = rotate(key)

In [80]:
key

array([[0, 0, 0],
       [1, 0, 0],
       [0, 1, 1]])

In [81]:
key_90

array([[0, 1, 0],
       [1, 0, 0],
       [1, 0, 0]])

In [82]:
# key의 1위치 저장
x,y = np.where(key_90 == 1,)
key_idx = [(x[i]+1,y[i]+1) for i in range(len(x))]

In [90]:
np.np.array(key_idx[0])

array([1, 2])

In [97]:
import numpy.linalg as lin

lin.eig(np.array(key_idx))

LinAlgError: Last 2 dimensions of the array must be square

In [101]:
np.array(key_idx)

array([[1, 2],
       [2, 1],
       [3, 1]])

In [125]:
key

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 0]])

In [126]:
lock

array([[0, 0, 0],
       [0, 0, 1],
       [0, 1, 0]])

In [127]:
lin.eig(lock)

(array([ 1., -1.,  0.]),
 array([[ 0.        ,  0.        ,  1.        ],
        [ 0.70710678,  0.70710678,  0.        ],
        [ 0.70710678, -0.70710678,  0.        ]]))

In [128]:
lin.eig(key)

(array([1., 1., 0.]),
 array([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]]))

In [111]:
key

array([[0, 0, 0],
       [1, 0, 0],
       [0, 1, 1]])

In [112]:
key_90 = rotate(key)

In [114]:
key_90

array([[0, 1, 0],
       [1, 0, 0],
       [1, 0, 0]])

In [113]:
lin.eig(key_90)

(array([ 0.,  1., -1.]),
 array([[ 0.        ,  0.57735027,  0.57735027],
        [ 0.        ,  0.57735027, -0.57735027],
        [ 1.        ,  0.57735027, -0.57735027]]))